# Generated by Django 3.1.3 on 2020-12-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=400)),
            ],
        ),
    ]
