# Generated by Django 3.1.3 on 2021-02-23 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='links',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('destination', models.URLField(unique=True)),
                ('source', models.URLField()),
                ('isTrine', models.BooleanField()),
                ('visited', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='page_results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('url', models.ForeignKey(db_column='url', on_delete=django.db.models.deletion.CASCADE, to='search.links', to_field='destination')),
            ],
        ),
        migrations.CreateModel(
            name='keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('times_on_page', models.IntegerField()),
                ('url', models.ForeignKey(db_column='destination', on_delete=django.db.models.deletion.CASCADE, to='search.links', to_field='destination')),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.ForeignKey(db_column='url', on_delete=django.db.models.deletion.CASCADE, to='search.links', to_field='destination'),
        ),
    ]
