# Generated by Django 3.1.3 on 2021-02-09 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_keywords_links_page_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.ForeignKey(db_column='destination', on_delete=django.db.models.deletion.CASCADE, to='search.links', to_field='destination'),
        ),
    ]
