# Generated by Django 3.1.3 on 2021-02-24 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210223_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.links'),
        ),
    ]
