# Generated by Django 3.1.3 on 2021-03-07 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20210224_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='pagerank',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='isTrine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='links',
            name='visited',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='edges',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pointA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointA', to='search.links')),
                ('pointB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointB', to='search.links')),
            ],
        ),
    ]
