# Generated by Django 3.1.3 on 2021-02-09 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20210209_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.ForeignKey(db_column='url', on_delete=django.db.models.deletion.CASCADE, to='search.links', to_field='destination'),
        ),
        migrations.AlterField(
            model_name='page_results',
            name='url',
            field=models.ForeignKey(db_column='url', on_delete=django.db.models.deletion.CASCADE, to='search.links', to_field='destination'),
        ),
    ]
