# Generated by Django 3.1.3 on 2021-03-30 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='links',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pagerank', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('destination', models.URLField(max_length=400, unique=True)),
                ('source', models.URLField(max_length=400)),
                ('isTrine', models.PositiveIntegerField(default=0)),
                ('visited', models.BooleanField(default=False)),
                ('parsed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField(max_length=400)),
                ('hashId', models.CharField(default='0000000000000000000000000000000000000000', max_length=40)),
                ('url', models.ForeignKey(db_column='url', on_delete=django.db.models.deletion.CASCADE, to='search.links', to_field='destination')),
            ],
        ),
        migrations.CreateModel(
            name='keywords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=20)),
                ('times_on_page', models.IntegerField()),
                ('is_substr', models.PositiveIntegerField(default=0)),
                ('word_len', models.PositiveIntegerField(default=0)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.links')),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=400)),
                ('source_url', models.ForeignKey(db_column='url', on_delete=django.db.models.deletion.CASCADE, to='search.links', to_field='destination')),
            ],
        ),
        migrations.CreateModel(
            name='edges',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pointA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointA', to='search.links')),
                ('pointB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointB', to='search.links')),
            ],
        ),
    ]
